name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
jobs:
  build:
    name: Create Release
    runs-on: windows-2019
    env:
      libraryName: hdf5
      cmakeInstallationPath: hdf5-installation
      tagName: hdf5-1_13_2 # target tag
      mingwTargetZip: hdf5-${{ github.ref_name }}-x86_64-posix-seh-rev0-8.1.0.zip
    steps:
      - name: check mingw version
        run: gcc --version
        
      - name: curl x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
        shell: cmd
        run:  cd /d ${{ github.workspace }} && curl https://github.com/2641797006/c/blob/master/GCC-zip/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z?raw=true -L --output x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z && dir && 7z.exe x x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
        
      - name: curl cmake-3.24.0-windows-x86_64.zip
        shell: cmd
        run: cd /d ${{ github.workspace }} && curl https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-x86_64.zip -L --output cmake-3.24.0-windows-x86_64.zip && dir && 7z.exe x cmake-3.24.0-windows-x86_64.zip
        
      - name: curl strawberry-perl-5.32.1.1-64bit-portable.zip
        shell: cmd
        run: |
          cd /d ${{ github.workspace }} && ^
          curl https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit-portable.zip -L --output strawberry-perl-5.32.1.1-64bit-portable.zip &&^
          dir && ^
          7z.exe x strawberry-perl-5.32.1.1-64bit-portable.zip -o"${{ github.workspace }}\strawberry-perl-5.32.1.1-64bit-portable"

      - name: git clone
        shell: cmd
        run: git clone --recursive https://github.com/HDFGroup/hdf5.git && cd hdf5 && git checkout ${{ env.tagName }}
        
      - name: cmake
        shell: cmd
        run: |
          set PATH=^
          ${{ github.workspace }}\mingw64;^
          ${{ github.workspace }}\mingw64\bin;^
          ${{ github.workspace }}\cmake-3.24.0-windows-x86_64\bin;^
          ${{ github.workspace }}\strawberry-perl-5.32.1.1-64bit-portable\perl\site\bin;^
          ${{ github.workspace }}\strawberry-perl-5.32.1.1-64bit-portable\perl\bin;^
          ${{ github.workspace }}\strawberry-perl-5.32.1.1-64bit-portable\c\bin;
          cd hdf5 &&^
          cmake.exe -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="build/${{ env.libraryName }}" -B./build &&^
          cd build && cmake --build . && cmake --install .
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "hdf5/build/${{ env.libraryName }}"
          filename: "${{ env.mingwTargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "hdf5/build/${{ env.libraryName }}/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
